"""BaseTables

Revision ID: 49521d64e350
Revises: 
Create Date: 2026-07-08 15:27:11.409008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49521d64e350'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'wounded', 'dead', name='status'), nullable=False),
    sa.Column('level', sa.Enum('beginer', 'confirmed', 'legend', name='level'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dangerousness', sa.Enum('easy', 'medium', 'mortal', name='dangerousness'), nullable=False),
    sa.Column('status', sa.Enum('registration', 'in_progress', 'finished', name='racestatus'), nullable=False),
    sa.Column('registration_price', sa.Integer(), nullable=False),
    sa.Column('cash_prize', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bettor_name', sa.String(), nullable=False),
    sa.Column('stake', sa.Integer(), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'won', 'lost', name='status'), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_speed', sa.Integer(), nullable=False),
    sa.Column('base_handling', sa.Integer(), nullable=False),
    sa.Column('shield', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], )
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('engine', 'thruster', 'cockpit', name='type'), nullable=False),
    sa.Column('boost_speed', sa.Integer(), nullable=False),
    sa.Column('boost_handling', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    op.drop_table('registrations')
    op.drop_table('pods')
    op.drop_table('bets')
    op.drop_table('races')
    op.drop_table('pilots')
    # ### end Alembic commands ###
